per_page: 10
validate:
  high_length: 255
  phone_length: 11
  normal_length: 50
  precision: 8
  scale: 2
  negative: -1
  min_pass: 6
product:
  per_page: 15
  expensive: 50
  trend_size: 8
  recently_size: 8
order:
  per_page: 10
order_item:
  per_page: 10
sort_name_asc: 1
sort_name_desc: 2
sort_price_asc: 3
sort_price_desc: 4
filter_price_low: 5
filter_price_normal: 6
filter_price_medium: 7
filter_price_high: 8
list_id: [1,2,3,4]
