validate:
  high_length: 255
  phone_length: 11
  normal_length: 50
  precision: 8
  scale: 2
  zero: 0
  min_pass: 6
product:
  per_page: 15
  expensive: 50
sort_name_asc: 1
sort_name_desc: 2
sort_price_asc: 3
sort_price_desc: 4
filter_price_low: 5
filter_price_normal: 6
filter_price_medium: 7
filter_price_hight: 8
